### ISSUE TITLE
Botrix config command to run bots at startup?

### ISSUE THREAD

**Issue by Langerz82** [borzh/botrix#2]
Hello,

I was wondering if you could implement the config.ini so you can load up bots at the start automatically by adding in "botrix bot add" into the config.

**Comment by borzh** [comment]
Sure will do.

**Comment by borzh** [comment]
You can set bots+players quota by using botrix command:
**botrix bot config quota X**
For example:
**botrix bot config quota 3** to have 3 bots at all times
or 
**botrix bot config** 1-3 to have 3 bots per player.
Set to 0 to disable quota.

You can put any of this into server.cfg or alike.
