### ISSUE TITLE
Linux - Server crashes only after a map change and issuing _restart or quit

### ISSUE THREAD

**Issue by nwb99** [borzh/botrix#3]
If I have botrix installed, load the server, and quit the server while it's still on the first map, it closes fine. However, if a changelevel occurs or I force one, and issue the quit command, the server crashes with the following:
```
free(): invalid pointer
Looking up breakpad interfaces from steamclient  
Calling BreakpadMiniDumpSystemInit  
assert_2018080803833_1.dmp[3864]: Uploading dump (out-of-process)  
/tmp/dumps/assert_2018080803833_1.dmp  
Aborted (core dumped)  
cat: hlds.3834.pid: No such file or directory  
email debug.log to linux@valvesoftware.com  
```
I start the server with -debug, but the debug.log contains no information.

**Comment by borzh** [comment]
Thanks, will check it out as soon as I can.

**Comment by nwb99** [comment]
Forgot to mention, this is HL2MP. Half-Life 2 Deathmatch.

**Comment by nwb99** [comment]
Oh yeah this has been resolved for a while. Can close the issue.

**Comment by borzh** [comment]
Thanks for letting me know, closing this.
