### ISSUE TITLE
Props go through botrix bots

### ISSUE THREAD

**Issue by ghost** [borzh/botrix#6]
https://www.youtube.com/watch?v=4lpW9cd__bk

A very common glitch that makes it less fun to play against bots

I would greatly appreciate it if you fixed this bug!

**Comment by nwb99** [comment]
I experience this issue on occasion and the bots will teleport back to where they were some point in the past. I'm assuming it's some kind of interpolation lag comp problem? No clue.

**Comment by borzh** [comment]
This is an engine's error, not plugin's.
