### ISSUE TITLE
"Cannot open interface VEngineServer023"

### ISSUE THREAD

**Issue by wrefgtzweve** [borzh/botrix#8]
I'm trying to use this mod with garrys mod which is also based on sdk 2013. 
It seems to fail in the first few steps.

This happens on startup and when `plugin_load` is used.
```
plugin_load addons/botrix
[Botrix] Cannot open interface VEngineServer023
Failed to load plugin "addons/botrix"
Unable to load plugin "addons/botrix"
```

**Comment by borzh** [comment]
Sorry garry's mod isn't supported yet
